import { Eye, EyeOff, ArrowRight, CheckCircle2 } from 'lucide-react';
import { useState, type FormEvent, type ReactNode } from 'react';
import { Link, useNavigate, useSearchParams } from 'react-router-dom';
import { z } from 'zod';
import { api } from '../api/client';
import { useAuthStore } from '../store/auth.store';
import { ErrorState, LoadingState } from '../components/ui';
import { useMutation } from '@tanstack/react-query';

const credentialsSchema = z.object({ email: z.string().email('Enter a valid email.'), password: z.string().min(8, 'Password must be at least 8 characters.') });
const registrationSchema = credentialsSchema.extend({ name: z.string().trim().min(2, 'Name must be at least 2 characters.') });
function apiError(error: unknown) { const response = (error as { response?: { status?: number; data?: { error?: { message?: string; issues?: Array<{ message?: string }> } } } }).response; const messages: Record<number, string> = { 401: 'Your session or credentials are invalid.', 403: 'You do not have permission to do that.', 422: 'Please check the submitted information.', 429: 'Too many attempts. Please wait and try again.', 500: 'The server could not complete the request.' }; return response?.data?.error?.issues?.[0]?.message ?? response?.data?.error?.message ?? messages[response?.status ?? 0] ?? 'Unable to complete your request.'; }
function AuthFrame({ title, eyebrow, children }: { title: string; eyebrow: string; children: ReactNode }) { return <main className="flex min-h-screen items-center justify-center bg-[#f4f8f7] px-5 py-10"><div className="w-full max-w-md"><Link to="/" className="font-display text-2xl font-bold text-slate-950">Skill<span className="text-cyan-600">Swap</span></Link><div className="mt-10 rounded-2xl border border-slate-200 bg-white p-7 shadow-sm md:p-9"><p className="eyebrow">{eyebrow}</p><h1 className="mt-3 font-display text-3xl font-bold text-slate-950">{title}</h1>{children}</div></div></main>; }
function PasswordField({ value, onChange, name = 'password' }: { value: string; onChange: (value: string) => void; name?: string }) { const [visible, setVisible] = useState(false); return <div className="relative"><input className="field pr-11" name={name} type={visible ? 'text' : 'password'} value={value} onChange={(event) => onChange(event.target.value)} autoComplete={name === 'password' ? 'current-password' : 'new-password'} /> <button className="absolute right-2 top-1/2 -translate-y-1/2 icon-button" type="button" onClick={() => setVisible(!visible)} aria-label={visible ? 'Hide password' : 'Show password'}>{visible ? <EyeOff size={17} /> : <Eye size={17} />}</button></div>; }
export function LoginPage() { const navigate = useNavigate(); const setSession = useAuthStore((state) => state.setSession); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const mutation = useMutation({ mutationFn: () => api.auth.login({ email, password }), onSuccess: ({ data }) => { setSession(data.data.user, data.data.accessToken); navigate('/dashboard'); }, onError: (error) => setError(apiError(error)) }); const submit = (event: FormEvent) => { event.preventDefault(); const parsed = credentialsSchema.safeParse({ email, password }); if (!parsed.success) { setError(parsed.error.issues[0].message); return; } setError(''); mutation.mutate(); }; return <AuthFrame eyebrow="Welcome back" title="Sign in to SkillSwap"><form className="mt-7 space-y-5" onSubmit={submit}><label className="label">Email<input className="field" type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" /></label><label className="label">Password<PasswordField value={password} onChange={setPassword} /></label>{error && <ErrorState message={error} />}{mutation.isPending ? <LoadingState label="Signing you in" /> : <button className="button-primary w-full" type="submit">Sign in <ArrowRight size={16} /></button>}<div className="flex justify-between text-sm"><Link className="text-cyan-700 hover:underline" to="/forgot-password">Forgot password?</Link><Link className="text-slate-500 hover:text-slate-900" to="/register">Create account</Link></div></form></AuthFrame>; }
export function RegisterPage() { const navigate = useNavigate(); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const mutation = useMutation({ mutationFn: () => api.auth.register({ name, email, password }), onSuccess: () => navigate('/login', { state: { registered: true } }), onError: (error) => setError(apiError(error)) }); const submit = (event: FormEvent) => { event.preventDefault(); const parsed = registrationSchema.safeParse({ name, email, password }); if (!parsed.success) { setError(parsed.error.issues[0].message); return; } setError(''); mutation.mutate(); }; return <AuthFrame eyebrow="Join the exchange" title="Create your account"><form className="mt-7 space-y-5" onSubmit={submit}><label className="label">Name<input className="field" value={name} onChange={(event) => setName(event.target.value)} autoComplete="name" /></label><label className="label">Email<input className="field" type="email" value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" /></label><label className="label">Password<PasswordField value={password} onChange={setPassword} name="newPassword" /></label>{error && <ErrorState message={error} />}{mutation.isPending ? <LoadingState label="Creating account" /> : <button className="button-primary w-full" type="submit">Create account <ArrowRight size={16} /></button>}<p className="text-center text-sm text-slate-500">Already registered? <Link className="text-cyan-700" to="/login">Sign in</Link></p></form></AuthFrame>; }
export function ForgotPasswordPage() { const [email, setEmail] = useState(''); const [done, setDone] = useState(false); const mutation = useMutation({ mutationFn: () => api.auth.forgotPassword(email), onSuccess: () => setDone(true) }); return <AuthFrame eyebrow="Account recovery" title="Reset your password"><form className="mt-7 space-y-5" onSubmit={(event) => { event.preventDefault(); if (z.string().email().safeParse(email).success) mutation.mutate(); }}>{done ? <div className="flex gap-3 rounded-lg bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 size={18} />If an account exists, a reset link has been sent.</div> : <><label className="label">Email<input className="field" type="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label>{mutation.error && <ErrorState message={apiError(mutation.error)} />}{mutation.isPending ? <LoadingState label="Sending recovery email" /> : <button className="button-primary w-full">Send reset link <ArrowRight size={16} /></button>}</>}<Link className="block text-center text-sm text-cyan-700" to="/login">Back to sign in</Link></form></AuthFrame>; }
export function ResetPasswordPage() { const [params] = useSearchParams(); const [password, setPassword] = useState(''); const [done, setDone] = useState(false); const mutation = useMutation({ mutationFn: () => api.auth.resetPassword({ token: params.get('token') ?? '', password }), onSuccess: () => setDone(true) }); return <AuthFrame eyebrow="Account recovery" title="Choose a new password"><form className="mt-7 space-y-5" onSubmit={(event) => { event.preventDefault(); if (password.length >= 8 && params.get('token')) mutation.mutate(); }}>{done ? <div className="rounded-lg bg-emerald-50 p-4 text-sm text-emerald-800">Password updated. <Link className="font-semibold underline" to="/login">Sign in</Link></div> : <><label className="label">New password<PasswordField value={password} onChange={setPassword} name="newPassword" /></label>{mutation.error && <ErrorState message={apiError(mutation.error)} />}{mutation.isPending ? <LoadingState label="Updating password" /> : <button className="button-primary w-full">Update password <ArrowRight size={16} /></button>}</>}</form></AuthFrame>; }
export function VerifyEmailPage() { const [params] = useSearchParams(); const mutation = useMutation({ mutationFn: () => api.auth.verifyEmail(params.get('token') ?? '') }); return <AuthFrame eyebrow="Email verification" title="Verify your email"><div className="mt-7 space-y-5">{mutation.isSuccess ? <div className="rounded-lg bg-emerald-50 p-4 text-sm text-emerald-800">Your email has been verified.</div> : mutation.error ? <ErrorState message={apiError(mutation.error)} /> : <button className="button-primary w-full" onClick={() => mutation.mutate()} disabled={!params.get('token') || mutation.isPending}>{mutation.isPending ? 'Verifying' : 'Verify email'} <ArrowRight size={16} /></button>}<Link className="block text-center text-sm text-cyan-700" to="/login">Back to sign in</Link></div></AuthFrame>; }
