import { useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, Check, CheckCheck, Circle, Send, WifiOff } from 'lucide-react';
import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { io, type Socket } from 'socket.io-client';
import { z } from 'zod';
import { api } from '../api/client';
import { EmptyState, ErrorState, LoadingState } from '../components/ui';
import { useAuthStore } from '../store/auth.store';

type Conversation = { id: string; userAId: string; userBId: string; updatedAt: string; userA: { id: string; name: string }; userB: { id: string; name: string }; request: { status: string; skill: { title: string } } };
type Message = { id: string; conversationId: string; senderId: string; content: string; createdAt: string; readAt?: string | null };
type ReceivedMessage = { messageId: string; conversationId: string; senderId: string; content: string; createdAt: string };
const schema = z.object({ content: z.string().trim().min(1, 'Message cannot be empty.').max(2000, 'Message cannot exceed 2,000 characters.') });
const socketUrl = new URL(import.meta.env.VITE_API_URL || '/api/v1', window.location.origin).origin;
const errorText = (error: unknown) => (error as { response?: { data?: { error?: { message?: string } } } }).response?.data?.error?.message ?? 'Unable to process the message.';
const initials = (name: string) => name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase();

function Sidebar({ items, selectedId, unread, userId, select }: { items: Conversation[]; selectedId: string | null; unread: Set<string>; userId?: string; select: (id: string) => void }) {
  return <aside className={`w-full shrink-0 border-r border-slate-200 bg-white md:w-80 ${selectedId ? 'hidden md:block' : ''}`}><div className="border-b border-slate-100 p-5"><p className="eyebrow">Inbox</p><h1 className="mt-2 font-display text-2xl font-bold text-slate-950">Conversations</h1></div>{items.length ? items.map((item) => { const other = item.userAId === userId ? item.userB : item.userA; return <button key={item.id} type="button" className={`flex w-full items-center gap-3 border-b border-slate-100 p-4 text-left hover:bg-slate-50 ${selectedId === item.id ? 'bg-cyan-50' : ''}`} onClick={() => select(item.id)}><span className="flex h-10 w-10 items-center justify-center rounded-full bg-cyan-100 text-xs font-bold text-cyan-800">{initials(other.name)}</span><span className="min-w-0 flex-1"><span className="flex justify-between gap-2"><strong className="truncate text-sm text-slate-800">{other.name}</strong>{unread.has(item.id) && <span className="h-2 w-2 rounded-full bg-cyan-500" />}</span><span className="mt-1 block truncate text-xs text-slate-500">{item.request.skill.title}</span></span></button>; }) : <div className="p-4"><EmptyState title="No conversations" message="Accept an exchange request to start chatting." /></div>}</aside>;
}

function Chat({ conversation, messages, userId, connected, typing, busy, error, back, send, typingEvent }: { conversation: Conversation; messages: Message[]; userId?: string; connected: boolean; typing: boolean; busy: boolean; error: string; back: () => void; send: (content: string) => void; typingEvent: (active: boolean) => void }) {
  const other = conversation.userAId === userId ? conversation.userB : conversation.userA;
  const [content, setContent] = useState(''); const bottom = useRef<HTMLDivElement>(null);
  useEffect(() => { bottom.current?.scrollIntoView({ behavior: 'smooth' }); }, [messages, typing]);
  const submit = (event: FormEvent) => { event.preventDefault(); const parsed = schema.safeParse({ content }); if (!parsed.success) return; send(parsed.data.content); setContent(''); typingEvent(false); };
  return <section className="flex min-h-[calc(100vh-8rem)] min-w-0 flex-1 flex-col bg-[#f8fbfa]"><header className="flex items-center justify-between border-b border-slate-200 bg-white px-4 py-4 md:px-6"><div className="flex items-center gap-3"><button type="button" className="icon-button md:hidden" onClick={back} aria-label="Back to conversations"><ArrowLeft size={18} /></button><span className="flex h-10 w-10 items-center justify-center rounded-full bg-cyan-100 text-xs font-bold text-cyan-800">{initials(other.name)}</span><div><h2 className="font-semibold text-slate-900">{other.name}</h2><p className="text-xs text-slate-500">{conversation.request.skill.title} exchange</p></div></div><span className={`flex items-center gap-1.5 text-xs font-semibold ${connected ? 'text-emerald-600' : 'text-slate-400'}`}>{connected ? <><Circle className="fill-current" size={9} />Online</> : <><WifiOff size={14} />Socket reconnecting</>}</span></header><div className="flex-1 overflow-y-auto px-4 py-6 md:px-8">{messages.length ? <div className="mx-auto max-w-3xl space-y-3">{[...messages].reverse().map((message) => { const mine = message.senderId === userId; return <div key={message.id} className={`flex ${mine ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[80%] rounded-2xl px-4 py-3 ${mine ? 'bg-slate-950 text-white' : 'bg-white text-slate-800 shadow-sm'}`}><p className="whitespace-pre-wrap text-sm leading-6">{message.content}</p><div className="mt-2 flex justify-end gap-1 text-[11px] opacity-70"><time>{new Date(message.createdAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}</time>{mine && (message.readAt ? <CheckCheck size={14} /> : <Check size={14} />)}</div></div></div>; })}{typing && <p className="text-xs text-slate-400">{other.name} is typing...</p>}<div ref={bottom} /></div> : <EmptyState title="No messages yet" message="Start the conversation with a clear exchange proposal." />}</div>{error && <p className="border-t border-rose-100 bg-rose-50 px-4 py-2 text-sm text-rose-700">{error}</p>}<form className="flex gap-3 border-t border-slate-200 bg-white p-4 md:p-6" onSubmit={submit}><input className="field" value={content} onChange={(event) => { setContent(event.target.value); typingEvent(event.target.value.length > 0); }} placeholder="Write a message..." aria-label="Message" /><button type="submit" className="button-primary shrink-0" disabled={busy || !content.trim()}>{busy ? 'Sending...' : <><Send size={16} />Send</>}</button></form></section>;
}

export default function MessagesPage() {
  const userId = useAuthStore((state) => state.user?.id); const token = useAuthStore((state) => state.accessToken); const client = useQueryClient();
  const [selectedId, setSelectedId] = useState<string | null>(null); const selectedRef = useRef<string | null>(null); const [socket, setSocket] = useState<Socket | null>(null); const [connected, setConnected] = useState(false); const [typing, setTyping] = useState(false); const [unread, setUnread] = useState<Set<string>>(new Set()); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const conversations = useQuery({ queryKey: ['conversations'], queryFn: async () => (await api.conversations.list()).data.data as Conversation[] });
  const history = useQuery({ queryKey: ['messages', selectedId], queryFn: async () => (await api.messages.list(selectedId!, { page: 1, limit: 100 })).data.data as Message[], enabled: Boolean(selectedId) });
  const selected = useMemo(() => conversations.data?.find((item) => item.id === selectedId) ?? null, [conversations.data, selectedId]);
  useEffect(() => { selectedRef.current = selectedId; }, [selectedId]);
  useEffect(() => { if (!token) return; const next = io(socketUrl, { auth: { token }, reconnection: true, reconnectionAttempts: Infinity }); setSocket(next); const received = (item: ReceivedMessage) => { if (item.conversationId !== selectedRef.current) { setUnread((current) => new Set(current).add(item.conversationId)); return; } client.setQueryData<Message[]>(['messages', item.conversationId], (current = []) => current.some((message) => message.id === item.messageId) ? current : [{ id: item.messageId, conversationId: item.conversationId, senderId: item.senderId, content: item.content, createdAt: item.createdAt, readAt: null }, ...current]); void api.messages.markRead(item.messageId); }; const start = (item: { conversationId: string; userId: string }) => { if (item.conversationId === selectedRef.current && item.userId !== userId) setTyping(true); }; const stop = (item: { conversationId: string; userId: string }) => { if (item.conversationId === selectedRef.current && item.userId !== userId) setTyping(false); }; next.on('connect', () => setConnected(true)).on('disconnect', () => { setConnected(false); setTyping(false); }).on('message:received', received).on('typing:start', start).on('typing:stop', stop); return () => { next.disconnect(); setSocket(null); }; }, [token, userId, client]);
  useEffect(() => { if (!socket || !selectedId) return; setTyping(false); socket.emit('conversation:join', selectedId, (result: { ok: boolean }) => { if (!result.ok) setSelectedId(null); }); setUnread((current) => { const next = new Set(current); next.delete(selectedId); return next; }); }, [socket, selectedId]);
  const send = async (content: string) => { if (!selectedId || busy) return; setBusy(true); setError(''); try { const response = await api.messages.create(selectedId, content); const message = response.data.data as Message; client.setQueryData<Message[]>(['messages', selectedId], (current = []) => current.some((item) => item.id === message.id) ? current : [message, ...current]); } catch (reason) { setError(errorText(reason)); } finally { setBusy(false); } };
  const typingEvent = (active: boolean) => { if (socket && selectedId && connected) socket.emit(active ? 'typing:start' : 'typing:stop', selectedId); };
  if (conversations.isPending) return <LoadingState label="Loading conversations" />; if (conversations.isError) return <ErrorState message={errorText(conversations.error)} />;
  return <section className="-mx-4 -my-6 flex min-h-[calc(100vh-4rem)] overflow-hidden border-t border-slate-200 md:-mx-8 md:-my-10"><Sidebar items={conversations.data ?? []} selectedId={selectedId} unread={unread} userId={userId} select={setSelectedId} />{selected ? history.isPending ? <div className="flex flex-1 items-center justify-center"><LoadingState label="Loading message history" /></div> : history.isError ? <div className="flex flex-1 items-center p-6"><ErrorState message={errorText(history.error)} /></div> : <Chat conversation={selected} messages={history.data ?? []} userId={userId} connected={connected} typing={typing} busy={busy} error={error} back={() => setSelectedId(null)} send={send} typingEvent={typingEvent} /> : <div className="hidden flex-1 items-center justify-center md:flex"><EmptyState title="Choose a conversation" message="Select an accepted exchange to open its authorized chat." /></div>}</section>;
}
