import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Bell, Check, ChevronLeft, ChevronRight, MessageCircle, ShieldAlert, Sparkles } from 'lucide-react';
import { useState } from 'react';
import { api } from '../api/client';
import { EmptyState, ErrorState, LoadingState, Toast, useToast } from '../components/ui';

type Notification = { id: string; type: 'REQUEST_CREATED' | 'REQUEST_ACCEPTED' | 'REQUEST_REJECTED' | 'NEW_MESSAGE' | 'MODERATION' | 'SYSTEM'; title: string; body: string; isRead: boolean; createdAt: string };
type Page = { data: Notification[]; pagination: { page: number; limit: number; total: number; totalPages: number } };
const icons = { REQUEST_CREATED: Bell, REQUEST_ACCEPTED: Check, REQUEST_REJECTED: Bell, NEW_MESSAGE: MessageCircle, MODERATION: ShieldAlert, SYSTEM: Sparkles };
const errorText = (error: unknown) => (error as { response?: { data?: { error?: { message?: string } } } }).response?.data?.error?.message ?? 'Unable to load notifications.';
function NotificationRow({ item, onRead }: { item: Notification; onRead: () => void }) { const Icon = icons[item.type]; return <article className={`flex gap-4 border-b border-slate-100 p-5 transition last:border-0 ${item.isRead ? 'bg-white' : 'bg-cyan-50/40'}`}><div className={`mt-0.5 flex h-10 w-10 shrink-0 items-center justify-center rounded-lg ${item.isRead ? 'bg-slate-100 text-slate-500' : 'bg-cyan-100 text-cyan-700'}`}><Icon size={18} /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900">{item.title}</h3><p className="mt-1 text-xs font-bold uppercase tracking-wide text-cyan-700">{item.type.replace('_', ' ').toLowerCase()}</p></div>{!item.isRead && <span className="h-2.5 w-2.5 shrink-0 rounded-full bg-cyan-500" />}</div><p className="mt-3 text-sm leading-6 text-slate-600">{item.body}</p><p className="mt-3 text-xs text-slate-400">{new Date(item.createdAt).toLocaleString()}</p>{!item.isRead && <button className="mt-3 text-xs font-bold text-cyan-700 hover:text-cyan-900" onClick={onRead}>Mark as read</button>}</div></article>; }
export default function NotificationsPage() { const client = useQueryClient(); const toast = useToast(); const [page, setPage] = useState(1); const query = useQuery({ queryKey: ['notifications', 'page', page], queryFn: async () => (await api.notifications.list({ page, limit: 10 })).data as Page }); const read = useMutation({ mutationFn: (id: string) => api.notifications.markRead(id), onSuccess: () => { void client.invalidateQueries({ queryKey: ['notifications'] }); } }); const allRead = useMutation({ mutationFn: api.notifications.markAllRead, onSuccess: () => { void client.invalidateQueries({ queryKey: ['notifications'] }); toast.notify('All notifications marked as read.'); }, onError: (error) => toast.notify(errorText(error)) }); if (query.isPending) return <LoadingState label="Loading notifications" />; if (query.isError) return <ErrorState message={errorText(query.error)} />; const result = query.data; return <section className="mx-auto max-w-4xl space-y-8"><header className="flex flex-col justify-between gap-5 border-b border-slate-200 pb-8 sm:flex-row sm:items-end"><div><p className="eyebrow">Stay in the loop</p><h1 className="mt-3 font-display text-4xl font-bold tracking-tight text-slate-950">Notifications</h1><p className="mt-3 text-slate-600">Requests, messages, moderation, and system updates in one place.</p></div><button className="button-secondary" onClick={() => allRead.mutate()} disabled={allRead.isPending}><Check size={15} />Mark all read</button></header>{result.data.length ? <div className="overflow-hidden rounded-xl border border-slate-200 bg-white">{result.data.map((item) => <NotificationRow key={item.id} item={item} onRead={() => read.mutate(item.id)} />)}</div> : <EmptyState title="You are all caught up" message="New activity will appear here." />}{result.pagination.totalPages > 1 && <div className="flex items-center justify-center gap-4"><button className="button-secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={16} />Previous</button><span className="text-sm font-semibold text-slate-600">Page {page} of {result.pagination.totalPages}</span><button className="button-secondary" disabled={page >= result.pagination.totalPages} onClick={() => setPage(page + 1)}>Next <ChevronRight size={16} /></button></div>}{toast.message && <Toast message={toast.message} onClose={toast.dismiss} />}</section>; }
